"""
Swagger / OpenAPI example payloads.

Kept separate from the schema definitions so the contracts stay readable.
``MUTUAL_MATCH_EXAMPLE`` is what Swagger UI pre-fills for
``POST /matchmaking/match-users`` so the endpoint can be executed with a
single click.
"""

from __future__ import annotations

from typing import Any, Dict

# ---------------------------------------------------------------------------
# Logged-in user
# ---------------------------------------------------------------------------

_AHMED: Dict[str, Any] = {
    "user_id": "user_ahmed",
    "name": "Ahmed Khan",
    "gender": "male",
    "age": 30,
    "height_cm": 178,
    "marital_status": "never_married",
    "mother_tongue": "Urdu",
    "religion": "Islam",
    "sect": "Sunni",
    "religious_practice": "practicing",
    "education": "masters",
    "education_field": "Computer Science",
    "profession": "Software Engineer",
    "profession_category": "Technology",
    "employment_status": "employed",
    "monthly_income": 350000,
    "location": {"city": "Islamabad", "country": "Pakistan"},
    "family_structure": "nuclear",
    "living_arrangement": "separate_house",
    "family_involvement": "moderate",
    "interests": ["Technology", "Travel", "Reading", "Cooking"],
    "hobbies": ["Hiking", "Chess"],
    "personality_traits": ["Analytical", "Calm", "Ambitious"],
    "smoking": False,
    "drinking": False,
    "diet": "Halal",
    "exercise": "regular",
    "social_lifestyle": "balanced",
    "marriage_timeline": "within_1_year",
    "children_preference": "want_children",
    "relocation": "negotiable",
    "career_expectation": "continue_career",
    "about_me": "Software engineer who enjoys travel and good conversation.",
}

_AHMED_PREFERENCES: Dict[str, Any] = {
    "gender": "female",
    "age_range": {"min": 24, "max": 30},
    "height_range": {"min_cm": 155, "max_cm": 172},
    "location": ["Islamabad", "Rawalpindi"],
    "country": ["Pakistan"],
    "marital_status": ["never_married"],
    "religion": ["Islam"],
    "sect": ["Sunni"],
    "religious_practice": ["practicing", "moderately_practicing"],
    "min_education": "bachelors",
    "preferred_field": ["Medicine", "Computer Science"],
    "profession": ["Doctor", "Teacher", "Software Engineer"],
    "employment_status": ["employed", "self_employed"],
    "income_range": {"min": 80000, "max": 400000, "currency": "PKR"},
    "family_structure": ["nuclear"],
    "living_arrangement": ["separate_house", "independent"],
    "family_involvement": ["moderate", "low"],
    "smoking": False,
    "diet": ["Halal"],
    "exercise": ["regular", "daily"],
    "social_lifestyle": ["balanced", "social"],
    "personality_traits": ["Calm", "Empathetic", "Ambitious"],
    "interests": ["Reading", "Travel", "Cooking"],
    "marriage_timeline": ["within_1_year", "within_6_months"],
    "children_preference": ["want_children"],
    "relocation": ["willing", "negotiable"],
    "career_expectation": ["continue_career", "flexible"],
    "deal_breakers": ["smoking"],
}

# ---------------------------------------------------------------------------
# The user list
# ---------------------------------------------------------------------------

_FATIMA: Dict[str, Any] = {
    "user_id": "user_fatima",
    "name": "Fatima Ali",
    "gender": "female",
    "age": 27,
    "height_cm": 163,
    "marital_status": "never_married",
    "mother_tongue": "Urdu",
    "religion": "Islam",
    "sect": "Sunni",
    "religious_practice": "practicing",
    "education": "masters",
    "education_field": "Medicine",
    "profession": "Doctor",
    "profession_category": "Healthcare",
    "employment_status": "employed",
    "monthly_income": 220000,
    "location": {"city": "Islamabad", "country": "Pakistan"},
    "family_structure": "nuclear",
    "living_arrangement": "separate_house",
    "family_involvement": "moderate",
    "interests": ["Reading", "Travel", "Cooking", "Art"],
    "personality_traits": ["Empathetic", "Calm", "Creative"],
    "smoking": False,
    "drinking": False,
    "diet": "Halal",
    "exercise": "regular",
    "social_lifestyle": "balanced",
    "marriage_timeline": "within_1_year",
    "children_preference": "want_children",
    "relocation": "negotiable",
    "career_expectation": "continue_career",
    "partner_preferences": {
        "gender": "male",
        "age_range": {"min": 28, "max": 35},
        "height_range": {"min_cm": 170, "max_cm": 190},
        "location": ["Islamabad"],
        "country": ["Pakistan"],
        "marital_status": ["never_married"],
        "religion": ["Islam"],
        "sect": ["Sunni"],
        "religious_practice": ["practicing"],
        "min_education": "masters",
        "preferred_field": ["Computer Science", "Engineering"],
        "profession": ["Software Engineer", "Doctor"],
        "employment_status": ["employed", "business_owner"],
        "income_range": {"min": 200000, "max": 800000, "currency": "PKR"},
        "family_structure": ["nuclear"],
        "living_arrangement": ["separate_house"],
        "family_involvement": ["moderate", "low"],
        "smoking": False,
        "diet": ["Halal"],
        "exercise": ["regular", "daily"],
        "social_lifestyle": ["balanced"],
        "personality_traits": ["Ambitious", "Calm"],
        "interests": ["Travel", "Reading"],
        "marriage_timeline": ["within_1_year"],
        "children_preference": ["want_children"],
        "relocation": ["negotiable", "willing"],
        "career_expectation": ["continue_career"],
        "deal_breakers": ["smoking"],
    },
}

_AYESHA: Dict[str, Any] = {
    "user_id": "user_ayesha",
    "name": "Ayesha Malik",
    "gender": "female",
    "age": 26,
    "height_cm": 158,
    "marital_status": "never_married",
    "mother_tongue": "Punjabi",
    "religion": "Islam",
    "sect": "Sunni",
    "religious_practice": "moderately_practicing",
    "education": "bachelors",
    "education_field": "Business Administration",
    "profession": "Marketing Manager",
    "profession_category": "Business",
    "employment_status": "employed",
    "monthly_income": 120000,
    "location": {"city": "Lahore", "country": "Pakistan"},
    "family_structure": "joint",
    "living_arrangement": "with_parents",
    "family_involvement": "high",
    "interests": ["Music", "Shopping", "Travel"],
    "personality_traits": ["Extroverted", "Creative"],
    "smoking": False,
    "drinking": False,
    "diet": "Halal",
    "exercise": "occasional",
    "social_lifestyle": "very_social",
    "marriage_timeline": "no_rush",
    "children_preference": "undecided",
    "relocation": "not_willing",
    "career_expectation": "flexible",
    "partner_preferences": {
        "gender": "male",
        "age_range": {"min": 27, "max": 33},
        "location": ["Lahore"],
        "country": ["Pakistan"],
        "marital_status": ["never_married"],
        "religion": ["Islam"],
        "sect": ["Sunni"],
        "min_education": "bachelors",
        "employment_status": ["employed", "business_owner"],
        "family_structure": ["joint"],
        "living_arrangement": ["with_parents"],
        "family_involvement": ["high"],
        "smoking": False,
        "social_lifestyle": ["very_social", "social"],
        "marriage_timeline": ["no_rush"],
        "children_preference": ["undecided", "want_children"],
        "relocation": ["not_willing"],
    },
}

_SANA: Dict[str, Any] = {
    "user_id": "user_sana",
    "name": "Sana Rehman",
    "gender": "female",
    "age": 29,
    "height_cm": 166,
    "marital_status": "divorced",
    "mother_tongue": "Urdu",
    "religion": "Islam",
    "sect": "Shia",
    "religious_practice": "practicing",
    "education": "doctorate",
    "education_field": "Computer Science",
    "profession": "Lecturer",
    "profession_category": "Education",
    "employment_status": "employed",
    "monthly_income": 180000,
    "location": {"city": "Rawalpindi", "country": "Pakistan"},
    "family_structure": "nuclear",
    "living_arrangement": "independent",
    "family_involvement": "low",
    "interests": ["Reading", "Technology", "Cooking"],
    "personality_traits": ["Analytical", "Calm"],
    "smoking": False,
    "drinking": False,
    "diet": "Halal",
    "exercise": "daily",
    "social_lifestyle": "reserved",
    "marriage_timeline": "within_6_months",
    "children_preference": "want_children",
    "relocation": "willing",
    "career_expectation": "continue_career",
    "partner_preferences": {
        "gender": "male",
        "age_range": {"min": 28, "max": 38},
        "religion": ["Islam"],
        "sect": ["Shia"],
        "min_education": "masters",
        "location": ["Rawalpindi", "Islamabad"],
        "smoking": False,
        "marriage_timeline": ["within_6_months", "immediately"],
        "children_preference": ["want_children"],
    },
}

_ZARA: Dict[str, Any] = {
    "user_id": "user_zara",
    "name": "Zara Sheikh",
    "gender": "female",
    "age": 25,
    "height_cm": 168,
    "marital_status": "never_married",
    "mother_tongue": "Urdu",
    "religion": "Islam",
    "sect": "Sunni",
    "religious_practice": "moderately_practicing",
    "education": "bachelors",
    "education_field": "Computer Science",
    "profession": "Software Engineer",
    "profession_category": "Technology",
    "employment_status": "employed",
    "monthly_income": 150000,
    "location": {"city": "Rawalpindi", "country": "Pakistan"},
    "family_structure": "nuclear",
    "living_arrangement": "independent",
    "family_involvement": "low",
    "interests": ["Technology", "Reading", "Travel"],
    "personality_traits": ["Ambitious", "Calm", "Analytical"],
    "smoking": False,
    "drinking": False,
    "diet": "Halal",
    "exercise": "daily",
    "social_lifestyle": "balanced",
    "marriage_timeline": "within_6_months",
    "children_preference": "want_children",
    "relocation": "willing",
    "career_expectation": "continue_career",
    "partner_preferences": {
        "gender": "male",
        "age_range": {"min": 26, "max": 34},
        "height_range": {"min_cm": 170, "max_cm": 195},
        "location": ["Islamabad", "Rawalpindi"],
        "country": ["Pakistan"],
        "marital_status": ["never_married"],
        "religion": ["Islam"],
        "sect": ["Sunni"],
        "religious_practice": ["practicing", "moderately_practicing"],
        "min_education": "bachelors",
        "preferred_field": ["Computer Science", "Engineering"],
        "employment_status": ["employed", "self_employed", "business_owner"],
        "income_range": {"min": 150000, "max": 900000, "currency": "PKR"},
        "family_structure": ["nuclear"],
        "living_arrangement": ["separate_house", "independent"],
        "family_involvement": ["low", "moderate"],
        "smoking": False,
        "diet": ["Halal"],
        "exercise": ["regular", "daily"],
        "social_lifestyle": ["balanced", "reserved"],
        "personality_traits": ["Analytical", "Ambitious"],
        "interests": ["Technology", "Travel"],
        "marriage_timeline": ["within_6_months", "within_1_year"],
        "children_preference": ["want_children"],
        "relocation": ["willing", "negotiable"],
        "career_expectation": ["continue_career"],
        "deal_breakers": ["smoking"],
    },
}


MUTUAL_MATCH_EXAMPLE: Dict[str, Any] = {
    "request_id": "req-swagger-demo-001",
    "logged_in_user": _AHMED,
    "partner_preferences": _AHMED_PREFERENCES,
    "users": [_FATIMA, _AYESHA, _SANA, _ZARA],
    "top_n": 10,
    "include_criterion_breakdown": True,
    "context": {"source": "swagger"},
}
