"""
AI Matchmaking Model

This module contains the data model representing the matchmaking
intelligence result. It is the structured output of the processing engine.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from matchmaking.schemas import (
    CompatibilityLevel,
    CriterionMatch,
    MatchStatus,
    ModelConfidence,
)


class AiMatchMakingModel(BaseModel):
    """Structured matchmaking result generated by the processing engine.

    This model contains all intelligence produced by the matchmaking
    system: scores, reasons, matched/mismatched criteria, and
    recommendations.

    It is the intermediate representation between the processing
    engine and the final response formatter.
    """

    # Identity
    candidate_id: str = Field(
        default="",
        description="The candidate's user ID",
    )

    # Core scoring
    match_score: int = Field(
        ge=0, le=100, description="Overall compatibility score (0-100)"
    )
    compatibility_level: CompatibilityLevel = Field(
        description="Human-readable compatibility level"
    )
    is_match: bool = Field(
        description="Whether this qualifies as a match"
    )
    match_status: MatchStatus = Field(
        description="Detailed match status"
    )

    # Detailed breakdown
    criterion_scores: Dict[str, float] = Field(
        default_factory=dict,
        description="Score for each individual criterion (0-100)",
    )
    criterion_matches: List[CriterionMatch] = Field(
        default_factory=list,
        description=(
            "Full per-criterion breakdown including weight, status and the "
            "human-readable reason behind each score"
        ),
    )

    # Preference analysis
    matched_preferences: List[str] = Field(
        default_factory=list,
        description="Preferences that are fully satisfied",
    )
    partial_matches: List[str] = Field(
        default_factory=list,
        description="Preferences that are partially satisfied",
    )
    mismatched_preferences: List[str] = Field(
        default_factory=list,
        description="Preferences that are not satisfied",
    )

    # Constraints
    deal_breakers_violated: List[str] = Field(
        default_factory=list,
        description="Deal breaker conditions that were violated",
    )
    hard_constraints_passed: bool = Field(
        default=True,
        description="Whether all hard constraints were satisfied",
    )
    failed_hard_constraints: List[str] = Field(
        default_factory=list,
        description="Hard constraints that failed",
    )

    # Explainability
    match_reasons: List[str] = Field(
        default_factory=list,
        description="Why they match (or would match)",
    )
    concerns: List[str] = Field(
        default_factory=list,
        description="Potential concerns or areas of mismatch",
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="Actionable recommendations for the backend/user",
    )

    # Confidence
    confidence_score: int = Field(
        ge=0, le=100,
        description="Model's confidence in its own assessment",
    )
    model_confidence: ModelConfidence = Field(
        default=ModelConfidence.MEDIUM,
        description="Confidence bucket required by the document: low / med / high",
    )

    # AI enhancement metadata
    ai_enhanced: bool = Field(
        default=False,
        description="Whether AI reasoning was applied",
    )
    ai_insights: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional AI-generated insights if available",
    )

    # Data quality
    data_completeness: float = Field(
        default=100.0,
        ge=0, le=100,
        description="How complete the input data was (affects confidence)",
    )

    def to_criterion_scores_dict(self) -> Dict[str, float]:
        """Return criterion scores for the final response."""
        return self.criterion_scores.copy()
